### PR TITLE
Develop/fetch-nearby-coffee-shops

### PR DESCRIPTION
**Pull request by LeiChen5**
This PR implements functionality to retrieve a JSON list of 20 nearby coffee shops at the current location using the Google Places API. The feature returns key details about each coffee shop, which can be used in the Map and Explore screens.

The following information is retrieved for each coffee shop:
- ID
- Name
- Address
- Location (latitude and longitude)
- Opening hours
- Rating
- Reviews
- Photos

The following composables have been created:
- FetchNearbyCoffeeShops.kt
- FetchNearbyCoffeeShopsTest.kt

The following files have been modified:

- build.gradle.kts: added dependencies for testing and configured buildConfig to use the API key
- libs.versions.toml: added version entries for test dependencies

### CODE REVIEW

**Comment by LeiChen5** [comment]
The 0% line coverage issue has been resolved. The root cause was that the CI workflow didn’t include a step to run unit tests. I’ve added this step to the CI.yaml file, so the CI workflow now runs the unit tests as well.
image

**Comment by veridisyndrome** [comment]
Instead of returning a List<JSONObject> shouldn't we return a List<Coffee>. I thought about creating a conversion function for that.
What do you think?

**Comment by jeongJ2004** [comment]
> Instead of returning a List shouldn't we return a List. I thought about creating a conversion function for that. What do you think?

What do you mean by this ? "Return a list instead of a list". It might create a confusion to Lei and other reviewers. Elaborate your question please :)

**Comment by LeiChen5** [comment]
The CI check continued to fail due to an "Unresolved reference 'MAPS_API_KEY'" error, indicating that CI was unable to retrieve the key from the GitHub secret, even though we had configured one for the Maps API key.
image
After multiple attempts, I discovered that the original secret might not have been correctly configured.So I created a new secret for **MAPS_API_KEY**, updated the corresponding lines in **CI.yaml** and **Android-build.yaml**, and the issue was resolved.
image

**Comment by jeongJ2004** [comment]
> The CI check continued to fail due to an "Unresolved reference 'MAPS_API_KEY'" error, indicating that CI was unable to retrieve the key from the GitHub secret, even though we had configured one for the Maps API key. image After multiple attempts, I discovered that the original secret might not have been correctly configured.So I created a new secret for **MAPS_API_KEY**, updated the corresponding lines in **CI.yaml** and **Android-build.yaml**, and the issue was resolved. image

Great! This was my bad, do you think that our coaches and others can see the map screen even though they don't have the maps api key in their local.properties ?

**Comment by LeiChen5** [comment]
> > The CI check continued to fail due to an "Unresolved reference 'MAPS_API_KEY'" error, indicating that CI was unable to retrieve the key from the GitHub secret, even though we had configured one for the Maps API key. image After multiple attempts, I discovered that the original secret might not have been correctly configured.So I created a new secret for **MAPS_API_KEY**, updated the corresponding lines in **CI.yaml** and **Android-build.yaml**, and the issue was resolved. image
> 
> Great! This was my bad, do you think that our coaches and others can see the map screen even though they don't have the maps api key in their local.properties ?

If they don't have the key in their local.properties they can see the map, but if you build the APK and install to your phone, you should able to see it normally since the CI process embeds the key into the APK

**Comment by veridisyndrome** [comment]
> > The CI check continued to fail due to an "Unresolved reference 'MAPS_API_KEY'" error, indicating that CI was unable to retrieve the key from the GitHub secret, even though we had configured one for the Maps API key. image After multiple attempts, I discovered that the original secret might not have been correctly configured.So I created a new secret for **MAPS_API_KEY**, updated the corresponding lines in **CI.yaml** and **Android-build.yaml**, and the issue was resolved. image
> 
> Great! This was my bad, do you think that our coaches and others can see the map screen even though they don't have the maps api key in their local.properties ?

We should try to build and download the APK to see if it works!! Can @jeongJ2004 do it since we don't have android phones~

**Review by veridisyndrome — APPROVED** [review]
LGTM!!! I already reviewed on my IDE. Amazing work~

**Pull request merged**
