### PR TITLE
Revert "feat: integrate SonarCloud, clean directory, and start overview screen"

### PR DESCRIPTION
**Pull request by tsogtb**
Reverts BrewR-EPFL/BrewR#26

### CODE REVIEW

**Comment by veridisyndrome** [comment]
?

**Comment by tsogtb** [comment]
> ?

Hey I wasn't aware that you didn't want commits on your branch so I wanted to hard reset to your last commit so we don't have bad commit messages

**Comment by veridisyndrome** [comment]
> > ?
> 
> Hey I wasn't aware that you didn't want commits on your branch so I wanted to hard reset to your last commit so we don't have bad commit messages

Hey, I appreciate your intention to keep our branch clean. However, I didn’t state that I didn’t want any commits on my branch. What I mentioned was the importance of adhering to the Conventional Commits convention that we all agreed to follow.
Please ensure that any future commits respect this guideline. You can go ahead and close your pull request for now. It’s crucial for the project’s success that we maintain a consistent approach to our commit messages.
Thank you for your understanding!

**Comment by tsogtb** [comment]
> > > ?
> > 
> > 
> > Hey I wasn't aware that you didn't want commits on your branch so I wanted to hard reset to your last commit so we don't have bad commit messages
> 
> Hey, I appreciate your intention to keep our branch clean. However, I didn’t state that I didn’t want any commits on my branch. What I mentioned was the importance of adhering to the Conventional Commits convention that we all agreed to follow. Please ensure that any future commits respect this guideline. You can go ahead and close your pull request for now. It’s crucial for the project’s success that we maintain a consistent approach to our commit messages. Thank you for your understanding;)

Oh you meant those prefixes like feat: fix: etc. I just looked at the link my bad

**Comment by veridisyndrome** [comment]
Not all the prefixes, but the commits in general. Please review this asap. [commits.pdf](https://github.com/user-attachments/files/17281201/commits.pdf)

**Pull request closed without merging**
