### PR TITLE
Develop/user private list screen

### PR DESCRIPTION
**Pull request by LeiChen5**
**Corresponding Issue:https://github.com/BrewR-EPFL/BrewR/issues/144**

Implement a private list feature within the user profile screen. This list will display coffee shops that the user has manually added from the explore screen. It allows users to quickly access and view details about their favorite coffee shops.

The following composable have been created:

- UserPrivateList.kt: This screen is designed to run a function that retrieves coffee shops and displays them as a private list. However, since the function hasn't been implemented yet, a mockCoffeeShop list is being used temporarily.
- UserPrivateListScreenTest.kt: Contains tests for the components of the UserPrivateListScreen

The following composable have been modified:

- MainActivity.kt: Added a navigation rule for UserPrivateListScreen.
- NavigationActions.kt: Introduced a route and screen definition for UserPrivateListScreen.
- UserMainProfile.kt: Updated a button to navigate to UserPrivateListScreen.

The following test tags have been added for testing:

- Scaffold: testTag("UserPrivateListScreen")
- TopAppBar: testTag("topBar")
- IconButton: testTag("goBackButton")
- content of lists: testTag("privateList")

Screenshot_20241205_185402

### CODE REVIEW

**Review by yixiaoi — COMMENTED** [review]
Good implementation of private list! but there is an affichement problem: 
image
when we click on a saved coffee shop, there are two "go back" buttons. From my point of view, you could use an ExpandableCard, or you could jump totally the whole page to the coffee information screen. NIce work and keep going!

**Comment by LeiChen5** [comment]
> Good implementation of private list! but there is an affichement problem: image when we click on a saved coffee shop, there are two "go back" buttons. From my point of view, you could use an ExpandableCard, or you could jump totally the whole page to the coffee information screen. NIce work and keep going!

Good idea! I'll try to do that.

**Comment by LeiChen5** [comment]
I updated the private list screen layout, now it looks like this when we click on the coffee shop image.
Screenshot_20241207_142135

**Review by yixiaoi — APPROVED** [review]
well done! Good implementation of layout

**Pull request merged**
