### PR TITLE
Develop/stylish UI

### PR DESCRIPTION
**Pull request by yixiaoi**
Corresponding issue https://github.com/BrewR-EPFL/BrewR/issues/101

Purpose: This PR enhances the app's UI to align with the app's theme and improve the overall user experience. Several visual updates have been made to make the app more aesthetically pleasing and user-friendly.

Changes Made:

1.Theme Color Updates
Various UI components' colors have been updated to reflect the app’s theme color, Coffee Brown, to create a more cohesive and visually appealing look that matches the app’s identity.
image

2. Journey Record UI Improvement:
The Journey Record screen has been redesigned to improve readability and user engagement. We have reduced the amount of text displayed and replaced some of it with icons. This change allows users to absorb information more easily, with a greater emphasis on visuals.
The images in the Journey Record screen now take up a larger portion of the screen to improve visibility and user interaction.
image image

3.Gallery Screen Layout Update:

The layout of the photos in the Gallery Screen has been updated to a fluid layout, offering a more dynamic and responsive design. This layout improves the user experience when browsing through their records, allowing them to view their images more smoothly and intuitively.

image image

UI changes:
signIn.kt
AddJourney.kt
EditJourney.kt
Gallery.kt
JourneyComponents.kt
JourneyRecord.kt
Overview.kt

Additional Notes:

The visual changes are aimed at enhancing user experience by creating a more seamless and enjoyable interface. The use of images over text makes the app feel more interactive and easier to navigate, especially on mobile devices.
We’ve also ensured that the design changes maintain the app's responsiveness across different screen sizes and orientations.

### CODE REVIEW

**Comment by yixiaoi** [comment]
This branch should only be merged after the 'Develop/implement location in add/edit screen' task is finished

**Review by HeeyounLee08 — APPROVED** [review]
It looks good to me!

**Review by LeiChen5 — APPROVED** [review]
WOW the new UI looks amazing!

**Comment by yixiaoi** [comment]
There is a little display problem

**Pull request merged**
