### PR TITLE
test(overview): implement tests for overview screen

### PR DESCRIPTION
**Pull request by LeiChen5**

### CODE REVIEW

**Comment by tsogtb** [comment]
Can you kotlin format your code please

**Comment by tsogtb** [comment]
I just updated the default quality gate and the new code definition in SonarCloud. I am just gonna trigger the CI again to see how it works out

**Review by tsogtb — APPROVED** [review]
Looks great, let's see what happens to main on sonar once we merge it because this PR includes 0 lines to cover.

**Comment by tsogtb** [comment]
> Looks great, let's see what happens to main on sonar once we merge it because this PR includes 0 lines to cover.

https://github.com/BrewR-EPFL/BrewR/runs/31418828034 here is the CI run after the merge for anyone who is interested in the current analysis details on main.
I updated the quality gate so that it look like this (please see below)
Please let me know if you think it needs further modifications
Other that that I learned that things get a bit tricky when we already merge untested stuff and add the test later. Here is the conversation I had with co-pilot and I thought it may be useful for future reference.

image
image

**Comment by LeiChen5** [comment]
Perfect! I'll do that next time. Thank you!

**Pull request merged**
